import { TScenario } from '@/core/data/types'
import { fromAstronomicalUnits } from '@/core/helpers/scaling'

export const Scenarios: TScenario[] = [
  {
    id: 'sol',
    name: 'Solar system',
    description: 'Solar system',
    preview: 'SolarSystem.jpg',
    size: 100,
    defaultCameraPosition: [0, fromAstronomicalUnits(2), fromAstronomicalUnits(2)],
    lights: ['Sun'],
    objects: [
      'Solar System Barycenter',
      'Sun',
      'Mercury',
      'Venus',
      'Earth System Barycenter',
      'Earth',
      'Mars System Barycenter',
      'Mars',
      'Ceres',
      'Jupiter System Barycenter',
      'Jupiter',
      'Saturn System Barycenter',
      'Saturn',
      'Uranus System Barycenter',
      'Uranus',
      'Neptune System Barycenter',
      'Neptune',
      'Pluto System Barycenter',
      'Pluto',
      'Haumea',
      'Makemake',
      'Eris',
      'Sedna',
      'Moon',
      'Io',
      'Europa',
      'Ganymede',
      'Callisto',
      'Mimas',
      'Enceladus',
      'Tethys',
      'Dione',
      'Rhea',
      'Titan',
      'Iapetus',
      'Miranda',
      'Ariel',
      'Umbriel',
      'Titania',
      'Oberon',
      'Triton',
      'Charon',
      'Dysnomia'
    ]
  },
  {
    id: 'toi_519',
    name: 'TOI-519 system',
    description: 'System with distant red-dwarf star and its satellite as hot-neptune',
    preview: 'TOI519System.jpg',
    size: 100,
    defaultCameraPosition: [0, fromAstronomicalUnits(0.03), fromAstronomicalUnits(0.03)],
    lights: ['TOI-519'],
    objects: ['TOI-519', 'TOI-519b']
  },
  {
    id: 'tatoo',
    name: 'Tatoo system',
    description: 'Approximate Tatoo system from Star Wars Universe',
    preview: 'TatooSystem.jpg',
    size: 100,
    defaultCameraPosition: [0, fromAstronomicalUnits(1.2), fromAstronomicalUnits(1.2)],
    lights: ['Tatoo I', 'Tatoo II'],
    objects: [
      'Tatoo Barycenter',
      'Tatoo I',
      'Tatoo II',
      'Tatooine',
      'Ohann',
      'Adriana',
      'Ghomrassen',
      'Guermessa',
      'Chenini',
      'Ohann I',
      'Ohann II',
      'Ohann III',
      'Adriana I',
      'Adriana II',
      'Adriana III',
      'Adriana IV'
    ]
  }
]
